name: clean_architecture_beer_app
description: A beer app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^4.3.0

  dio: ^4.0.6
  retrofit: ^3.0.1+1

  flutter_bloc: ^8.1.1
  get_it: ^7.2.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  build_runner: ^2.1.8
  retrofit_generator: ^4.0.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
